apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4-arm64
spec:
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.0-beta.0/vmlinuz-arm64
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyS0
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.platform=metal
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.5.0-beta.0/initramfs-arm64.xz
